version: "3.9"

services:
  database:
    image: mongo
    container_name: database_desafio
    restart: always
    env_file: ./.env
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
  database-seed:
    build: ./seed
    links: 
      - database
    depends_on:
      - database
  app:
    depends_on:
      - database
      - database-seed
    build: .
    container_name: desafio_node
    restart: always
    ports: 
      - 5000:5000
    volumes: 
      - .:/usr/app
    links: 
      - database

volumes:
  db: