version: '3.8'
services:
  node_api:
    container_name: node_api
    build: .
    ports:
      - ${API_PORT}:${API_PORT}
    env_file:
      - .env
    depends_on: 
      - database
    volumes:
      - .:/home/app
      - /home/app/node_modules
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  database:
    container_name: mongodb
    image: mongo
    restart: always 
    ports:
      - ${DB_PORT}:27017
    environment: 
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    volumes: 
      - mongodb:/data/db

volumes: 
  mongodb: